server:
  port: 8080
  servlet:
    context-path: /langora

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: ${APP_NAME}
  banner:
    location: banner.txt
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        base-url: ${OPEN_AI_API_URL}
        completions-path: "${OPEN_AI_COMPLETIONS_PATH}"
        options:
          model: ${OPEN_AI_MODEL}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

google:
  client-id: ${GOOGLE_CLIENT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SECRET}