server:
  port: 8080
  servlet:
    context-path: /langora

spring:
  application:
    name: langora-backend
  banner:
    location: banner.txt
  datasource:
    url: "jdbc:postgresql://localhost:5432/identity_service_db"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  signerKey: "ci927jBnQ4GsVEqj6ClN77nEFVMbcK4ZDq79UA6StkxWkOZVHGHNZc2HnjoUwiCX"
  valid-duration: 36000 # in seconds
  refreshable-duration: 36000 # in seconds